### ISSUE TITLE
Display the grid

### ISSUE THREAD

**Issue by fcollonval** [voila-dashboards/voila-gridstack#89]
Displaying the background grid would help guide the user:

![image](https://user-images.githubusercontent.com/8435071/111813877-1286bc00-88da-11eb-969d-4c6ffd89ab17.png)

As suggested in https://github.com/gridstack/gridstack.js/issues/662, this could be achieved through CSS:

```css
.grid-stack {
background-image: linear-gradient(rgb(224, 224, 224) 1px, transparent 1px), linear-gradient(90deg, rgb(224, 224, 224) 1px, transparent 0px), linear-gradient(rgba(255, 255, 255, 0.3) 5px, transparent 100px), linear-gradient(90deg, rgba(255, 255, 255, 0.3) 5px, transparent 100px);
background-size: 100px 60px, calc(8.33333% + 0px) 100px, 20px 20px, 20px 20px;
background-position: -2px -2px, -1px -2px, -1px -1px, -1px -1px;
}
```

But it would be function of the grid widget as the number of column influence the _100% / N_ in background size.

The _inset_ on `.grid-stack-instance-xyz > .grid-stack-item > .grid-stack-item-content` would probably need to be lower than 10px too.
